# Generated by Django 4.0 on 2022-01-11 06:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('rollno', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=60)),
                ('dob', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Mark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks', models.IntegerField()),
                ('grade', models.CharField(max_length=1)),
                ('rollno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id', to='student.student')),
            ],
        ),
    ]
